apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-none
  namespace: default
spec: 
  selector:  
    app: myapp  
    release: canary 
  clusterIP: None
  type: ClusterIP
  ports: 
  - port: 80 
    targetPort: 80  