#kubectl create role  pod-reader --verb=get,list,watch --resource=pods --dry-run=client -o yaml >role-demo.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-reader
  #namespace: default
rules:
- apiGroups:
  - ""
  resources:
   - pods
  verbs:
    - get
    - list
    - watch