apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-required
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values: 
            - foo
            - bar