apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-tolerate-demo
  namespace: default
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myapp #删除kubectl delete rs myapp
      realease: canary 
  template:
    metadata:
      labels:
        app: myapp  
        realease: canary 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
      tolerations:
      - key: "runEnv"
        operator: "Equal"
        value: "prod"
        effect: "NoExecute"
        tolerationSeconds: 20