#依赖于 6-deploy-demo.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec: 
  selector:  
    app: myapp  
    release: canary 
  clusterIP: 10.99.99.99  
  type: NodePort
  ports: 
  - port: 80 
    targetPort: 80  
    nodePort: 30080 #可以不定指，会动态分配
  #sessionAffinity: ClientIp 
  #默认值None,(Affinit密切关系，姻亲关系),同一客户端请求后端使用同一个pod处理