apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-preferred
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: nginx:latest
  affinity:
    nodeAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - preference:
         matchExpressions:
         - key: zone
           operator: In
           values:
            - foo
            - bar
       weight: 60