
apiVersion: v1
kind: Pod
metadata:
  name: pods-frontend
  labels:
    app: myapp
    tire: frontend
spec:
  containers:
    - name: myapp
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pods-db
  labels:
    app: redis
    tire: db
spec:
#  containers:
#    - name: redis
#      image: redis:latest
  containers:
    - name: busybox
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh","-c"，"sleep 3600"]
  affinity:
    podAffinity:
    #podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
         matchExpressions:
         -  {key: app, operator: In, values: ["myapp"]}
       topologyKey: kubernetes.io/hostname