apiVersion: v1
kind: Pod
metadata:
  name: pods-cpu-limits
  labels:
    app: myapp
    tire: frontend
spec:
  containers:
    - name: stress-ng
      image: ikubernetes/stress-ng:latest      
      command: ["/usr/bin/stress-ng","-c 1","--metrics-brief" ] #-c1 表示对cpu使用1个worker测试 -m 1表示对内存  
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        #limits: #QoS Class:       Burstable
        #  cpu: "500m"
        #  memory: "200Mi"
        limits:  #QoS Class:       Guaranteed
          cpu: "200m"
          memory: "128Mi"