package cxf_video.wsdl2java_gen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-20T13:48:30.434+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://cxf_video/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf_video/", className = "cxf_video.wsdl2java_gen.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf_video/", className = "cxf_video.wsdl2java_gen.SayHiResponse")
    @WebResult(name = "sayHiResult", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "speak", targetNamespace = "")
        java.lang.String speak
    );
}
