/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package hadoop_not_offen.avro.transfer;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface DemoService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"DemoService\",\"namespace\":\"hadoop.avro.transfer\",\"types\":[{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"sex\",\"type\":\"boolean\"},{\"name\":\"salary\",\"type\":\"double\"},{\"name\":\"childrenCount\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"QueryParameter\",\"fields\":[{\"name\":\"ageStart\",\"type\":\"int\"},{\"name\":\"ageEnd\",\"type\":\"int\"}]}],\"messages\":{\"ping\":{\"request\":[],\"response\":\"string\"},\"getPersonList\":{\"request\":[{\"name\":\"queryParameter\",\"type\":\"QueryParameter\"}],\"response\":{\"type\":\"array\",\"items\":\"Person\"}}}}");
  /**
   */
  java.lang.CharSequence ping() throws org.apache.avro.AvroRemoteException;
  /**
   */
  java.util.List<hadoop_not_offen.avro.transfer.Person> getPersonList(hadoop_not_offen.avro.transfer.QueryParameter queryParameter) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends DemoService {
    public static final org.apache.avro.Protocol PROTOCOL = hadoop_not_offen.avro.transfer.DemoService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getPersonList(hadoop_not_offen.avro.transfer.QueryParameter queryParameter, org.apache.avro.ipc.Callback<java.util.List<hadoop_not_offen.avro.transfer.Person>> callback) throws java.io.IOException;
  }
}