/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package hadoop_not_offen.avro.transfer;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class QueryParameter extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2654925591450355712L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"QueryParameter\",\"namespace\":\"hadoop.avro.transfer\",\"fields\":[{\"name\":\"ageStart\",\"type\":\"int\"},{\"name\":\"ageEnd\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<QueryParameter> ENCODER =
      new BinaryMessageEncoder<QueryParameter>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<QueryParameter> DECODER =
      new BinaryMessageDecoder<QueryParameter>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<QueryParameter> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<QueryParameter> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<QueryParameter>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this QueryParameter to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a QueryParameter from a ByteBuffer. */
  public static QueryParameter fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int ageStart;
  @Deprecated public int ageEnd;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public QueryParameter() {}

  /**
   * All-args constructor.
   * @param ageStart The new value for ageStart
   * @param ageEnd The new value for ageEnd
   */
  public QueryParameter(java.lang.Integer ageStart, java.lang.Integer ageEnd) {
    this.ageStart = ageStart;
    this.ageEnd = ageEnd;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ageStart;
    case 1: return ageEnd;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ageStart = (java.lang.Integer)value$; break;
    case 1: ageEnd = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ageStart' field.
   * @return The value of the 'ageStart' field.
   */
  public java.lang.Integer getAgeStart() {
    return ageStart;
  }

  /**
   * Sets the value of the 'ageStart' field.
   * @param value the value to set.
   */
  public void setAgeStart(java.lang.Integer value) {
    this.ageStart = value;
  }

  /**
   * Gets the value of the 'ageEnd' field.
   * @return The value of the 'ageEnd' field.
   */
  public java.lang.Integer getAgeEnd() {
    return ageEnd;
  }

  /**
   * Sets the value of the 'ageEnd' field.
   * @param value the value to set.
   */
  public void setAgeEnd(java.lang.Integer value) {
    this.ageEnd = value;
  }

  /**
   * Creates a new QueryParameter RecordBuilder.
   * @return A new QueryParameter RecordBuilder
   */
  public static hadoop_not_offen.avro.transfer.QueryParameter.Builder newBuilder() {
    return new hadoop_not_offen.avro.transfer.QueryParameter.Builder();
  }

  /**
   * Creates a new QueryParameter RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new QueryParameter RecordBuilder
   */
  public static hadoop_not_offen.avro.transfer.QueryParameter.Builder newBuilder(hadoop_not_offen.avro.transfer.QueryParameter.Builder other) {
    return new hadoop_not_offen.avro.transfer.QueryParameter.Builder(other);
  }

  /**
   * Creates a new QueryParameter RecordBuilder by copying an existing QueryParameter instance.
   * @param other The existing instance to copy.
   * @return A new QueryParameter RecordBuilder
   */
  public static hadoop_not_offen.avro.transfer.QueryParameter.Builder newBuilder(hadoop_not_offen.avro.transfer.QueryParameter other) {
    return new hadoop_not_offen.avro.transfer.QueryParameter.Builder(other);
  }

  /**
   * RecordBuilder for QueryParameter instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<QueryParameter>
    implements org.apache.avro.data.RecordBuilder<QueryParameter> {

    private int ageStart;
    private int ageEnd;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(hadoop_not_offen.avro.transfer.QueryParameter.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ageStart)) {
        this.ageStart = data().deepCopy(fields()[0].schema(), other.ageStart);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ageEnd)) {
        this.ageEnd = data().deepCopy(fields()[1].schema(), other.ageEnd);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing QueryParameter instance
     * @param other The existing instance to copy.
     */
    private Builder(hadoop_not_offen.avro.transfer.QueryParameter other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ageStart)) {
        this.ageStart = data().deepCopy(fields()[0].schema(), other.ageStart);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ageEnd)) {
        this.ageEnd = data().deepCopy(fields()[1].schema(), other.ageEnd);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'ageStart' field.
      * @return The value.
      */
    public java.lang.Integer getAgeStart() {
      return ageStart;
    }

    /**
      * Sets the value of the 'ageStart' field.
      * @param value The value of 'ageStart'.
      * @return This builder.
      */
    public hadoop_not_offen.avro.transfer.QueryParameter.Builder setAgeStart(int value) {
      validate(fields()[0], value);
      this.ageStart = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ageStart' field has been set.
      * @return True if the 'ageStart' field has been set, false otherwise.
      */
    public boolean hasAgeStart() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ageStart' field.
      * @return This builder.
      */
    public hadoop_not_offen.avro.transfer.QueryParameter.Builder clearAgeStart() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ageEnd' field.
      * @return The value.
      */
    public java.lang.Integer getAgeEnd() {
      return ageEnd;
    }

    /**
      * Sets the value of the 'ageEnd' field.
      * @param value The value of 'ageEnd'.
      * @return This builder.
      */
    public hadoop_not_offen.avro.transfer.QueryParameter.Builder setAgeEnd(int value) {
      validate(fields()[1], value);
      this.ageEnd = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ageEnd' field has been set.
      * @return True if the 'ageEnd' field has been set, false otherwise.
      */
    public boolean hasAgeEnd() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ageEnd' field.
      * @return This builder.
      */
    public hadoop_not_offen.avro.transfer.QueryParameter.Builder clearAgeEnd() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public QueryParameter build() {
      try {
        QueryParameter record = new QueryParameter();
        record.ageStart = fieldSetFlags()[0] ? this.ageStart : (java.lang.Integer) defaultValue(fields()[0]);
        record.ageEnd = fieldSetFlags()[1] ? this.ageEnd : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<QueryParameter>
    WRITER$ = (org.apache.avro.io.DatumWriter<QueryParameter>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<QueryParameter>
    READER$ = (org.apache.avro.io.DatumReader<QueryParameter>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
