logging:
  level:
    root: info
 
 
#---Dubbo
dubbo:
  application:
    name: my-dubbo-provider
  protocol: 
    name: dubbo
    port: 20881
  registry:
    id: my-dubbo-provider
    #address: nacos://127.0.0.1:8848
    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: nacos://127.0.0.1:8848
#  metadata-report:
#    address: nacos://127.0.0.1:8848
    