package corba.helloApp;

/**
* corba/helloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, August 23, 2012 4:27:49 PM GMT+08:00
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.helloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (corba.helloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.helloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.helloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.helloApp.HelloHelper.type ();
  }

}
