logging:
  level:
    org: info
    
#--config for *.mvc
#spring:
#  mvc:
#    pathmatch:
#      use-suffix-pattern: false
#      use-registered-suffix-pattern: true
#    contentnegotiation:
#      favor-path-extension: false    