
server:
  port: 8080 
spring:
  application:
    name: service-sidecar


eureka:
  instance:
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health.json
  
  
  
