module corba.two
{
	interface grid 
	{
		 readonly attribute short height; 
		 readonly attribute short width; 
		 void set(in short row, in short col, in long value);
		 long get(in short row, in short col); 
	};
};