spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8769
server:
  port: 8768

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露微服务的所有监控端口,生产环境应该只暴露部分
#  endpoint:
#    health:
#      show-details: ALWAYS
