spring:
  profiles:
    active: usage_message
#used for rabbitmq

#  redis:  
#    cluster:  
#      nodes:
#        - 172.16.35.35:7000
#        - 172.16.35.35:7001
#        - 172.16.35.35:7002
#        - 172.16.35.35:7003
#        - 172.16.35.35:7004
#        - 172.16.35.35:7005
logging:
  level:
    org: info

    
my-props: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2
    
    