/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_TestJavaNative */

#ifndef _Included_jni_TestJavaNative
#define _Included_jni_TestJavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_TestJavaNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_TestJavaNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
