logging:
  level:
    root: info
 
 
#---Dubbo
dubbo:
  application:
    name: my-dubbo-consumer
  protocol:
    name: dubbo
  registry:
    #address: nacos://127.0.0.1:8848
    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: nacos://127.0.0.1:8848
#  metadata-report:
#    address: nacos://127.0.0.1:8848
    