server:
  port: 8888
  
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #ddl-auto: update 
      ddl-auto: create 
      
  datasource:
    username: zh
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    #使用hikari数据源
    separator: /; #为存储过程用
logging:
  level:
    root: info
    
    
    