foo: bar-dev
#pass: '{cipher}a5777de9cc08726c9137bfea227b00526dd3ec501ce6f365218ac564a47b8f90'
pass: '{cipher}AQB+4sxGhOmQZyoLjEITWHTrNsBhmDKiHfuv31nuVAaENeXa7tbutAw4YGx8h8Ad0Qczo+IE2nh7BgddEqt37aAiuv5uaaMcafbyRTREaiCaMp5Iszbc7Jwk/082SnyqUJLmfBROLNq372uwZBTVA01VVKpS9AHUL39H6kyl0A9ONEfRBoLccU+51XfrYB6rj4sEh5+UwZugfKJEaa0o+0oSA6uhETGEdH38gxp64id+TPUtDL7dnKcNZ580TSB462VhT8XRPWikG13VpOo8terlOG2CGqNUwPraUaTN+aB1oQ6j7jIOkLaErzS4k/vrrqSIiYXavhDNdsNqv5ZwtZp8l21Ahbk/CHyVW0+6RZwQaA4diULhxWpVVJ7NenrNTMc='

