eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
    
feign:
  hystrix:
    enabled: true
#  httpclient:
#    enabled: true
#  okhttp:
#    enabled: false 

#对第一次请求就是失败，原因第一次请求返回时间过长
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
 