
logging:  level:    com.zh.service: debug
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
    
feign:
  client:
    config:
      default: #可是feigName
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        
  hystrix:
    enabled: false
    #enabled: true #会使用新线程，threadLocal丢失，RequestContextHolder.getRequestAttributes()为null,除非修改Hystrix使用SEMAPHORE
    
  circuitbreaker:  #pom.xml要加spring-cloud-starter-circuitbreaker-resilience4j，可能要2020版本
    #enabled: true  #会使用新线程，threadLocal丢失
    enabled: false 
      
#  httpclient:
#    enabled: true
#  okhttp:
#    enabled: false 

  #compression:
    #response:
    #  enabled: true #如加了这个配置，可不用实现Decoder做gzip解码
    #request:    #  enabled: true #如实现RequestInterceptor了再加这个可能没用
      
#对第一次请求就是失败，原因第一次请求返回时间过长
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
 