// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright(c) 2002 - 2010 Progress Software Corporation (PSC).  All
// rights reserved.  Use, reproduction, transfer, publication or
// disclosure is prohibited except as specifically provided for in
// your License Agreement with PSC.
//
// **********************************************************************

// Version: 4.3.4

package corba.hello;

//
// IDL:Hello:1.0
//
/***/

public interface HelloOperations
{
    //
    // IDL:Hello/say_hello:1.0
    //
    /***/

    void
    say_hello();
}
