// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright(c) 2002 - 2010 Progress Software Corporation (PSC).  All
// rights reserved.  Use, reproduction, transfer, publication or
// disclosure is prohibited except as specifically provided for in
// your License Agreement with PSC.
//
// **********************************************************************

// Version: 4.3.4

package corba.hello;

//
// IDL:Hello:1.0
//
final public class HelloHolder implements org.omg.CORBA.portable.Streamable
{
    public Hello value;

    public
    HelloHolder()
    {
    }

    public
    HelloHolder(Hello initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = HelloHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        HelloHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return HelloHelper.type();
    }
}
